title: Belkirk College of Engineering
short_title: Belkirk
description: The Forestry.io Prouct Tour Demo
collections:
  people:
    title: People
    output: true
    permalink: "/about/people/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  publications:
    title: Publications
    output: false
    permalink: "/publications/:path/"
gems:
  - jekyll-menus
  - jekyll-feed
